/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package panels;

import com.mycompany.analysisapp.*;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.awt.Component;

import java.io.File;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class UsernameCheckPanel extends javax.swing.JFrame {

    private String selectedUsername;
    private User selectedUser;

    /**
     * Creates new form UsernameCheckPanel
     */
    public UsernameCheckPanel() {
        initComponents();
    }

    public User getUser() {
        return this.selectedUser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameTextField = new javax.swing.JTextField();
        usernameButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usernameTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        usernameButton.setBackground(new java.awt.Color(0, 255, 0));
        usernameButton.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        usernameButton.setText("Check User");
        usernameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel1.setText("Kullanıcı Adı :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(usernameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(81, 81, 81))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(51, 51, 51)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(usernameButton)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameButtonActionPerformed
        String filepath = "src/main/java/jsonfiles/twitter_data.json";
        ObjectMapper objectMapper = new ObjectMapper();

        try {
            CustomLinkedList<User> userList = new CustomLinkedList<>();
            User[] users = objectMapper.readValue(new File(filepath), User[].class);
            for (User user : users) {
                userList.insertNode(user);
            }
            selectedUsername = usernameTextField.getText();

            CustomNode<User> tempUser = userList.getHead();
            while (tempUser != null) {
                if (tempUser.getData().getUsername().equals(selectedUsername)) {
                    selectedUser = tempUser.getData();
                    break;
                } else {
                    selectedUser = null;
                }
                tempUser = tempUser.getNext();
            }

            if (selectedUser == null) {
                JOptionPane.showMessageDialog(null, "Kullanıcı Bulunamadı!", "Kullanıcı Penceresi", JOptionPane.ERROR_MESSAGE);
            } else if (selectedUser != null) {

                CustomLinkedList followersList = new CustomLinkedList();
                CustomLinkedList followingList = new CustomLinkedList();

                for(String follower1 : selectedUser.getFollowers()){
                    followersList.insertNode(follower1);
                }
                
                for(String following1 : selectedUser.getFollowing()){
                    followingList.insertNode(following1);
                }

                JFrame frame = new JFrame(selectedUsername + " GRAPH " + "( KIRMIZI -> TAKİPÇİLER ) ( MAVİ -> TAKİP ETTİKLERİ )");
                UserGraphPanel graphPanel = new UserGraphPanel(selectedUser.getUsername(),followersList,followingList);
                frame.add(graphPanel);
                frame.setSize(2000, 2000);

                frame.setVisible(true);
            }

        } catch (IOException e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_usernameButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsernameCheckPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsernameCheckPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsernameCheckPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsernameCheckPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsernameCheckPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton usernameButton;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
